php:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/php/dev/Dockerfile
    mem_limit: "512M"
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: ./api
        target: /usr/share/nginx/html/api